# Generated by Django 5.2 on 2026-05-10 09:41

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название сайта')),
                ('description', models.TextField(verbose_name='Описание сайта')),
                ('logo', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='logo/', verbose_name='Логотип')),
                ('icon', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='icon/', verbose_name='Иконка')),
                ('locate', models.CharField(max_length=100, verbose_name='Адрес')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=100, verbose_name='Телефон')),
                ('work_schedule', models.CharField(max_length=100, verbose_name='Режим работы')),
                ('whatsapp', models.URLField(verbose_name='Whatsapp')),
                ('telegram', models.URLField(verbose_name='Telegram')),
                ('instagram', models.URLField(verbose_name='Instagram')),
                ('facebook', models.URLField(verbose_name='Facebook')),
            ],
            options={
                'verbose_name': '1) Настройки',
                'verbose_name_plural': '1) Настройки',
            },
        ),
    ]
