# Generated by Django 6.0.3 on 2026-05-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='default_staff_password',
            field=models.CharField(blank=True, max_length=128, verbose_name='Пароль по умолчанию для сотрудников'),
        ),
    ]
