#!/bin/bash
# ────────────────────────────────────────────────────────────────
# KIKI Academy — интерактивный деплой
# Запрашивает домен, email, данные суперюзера → разворачивает всё
# ────────────────────────────────────────────────────────────────
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
COMPOSE_FILE="$SCRIPT_DIR/docker-compose.prod.yml"
COMPOSE="docker compose -f $COMPOSE_FILE"
ENV_FILE="$PROJECT_ROOT/.env"

C_GREEN='\033[0;32m'
C_BLUE='\033[0;34m'
C_YELLOW='\033[1;33m'
C_RED='\033[0;31m'
C_RESET='\033[0m'

info()  { echo -e "${C_BLUE}→${C_RESET} $1"; }
ok()    { echo -e "${C_GREEN}✓${C_RESET} $1"; }
warn()  { echo -e "${C_YELLOW}⚠${C_RESET} $1"; }
fail()  { echo -e "${C_RED}✗ $1${C_RESET}"; exit 1; }

# ─── 0. Проверка зависимостей ──────────────────────────────────
echo ""
echo "════════════════════════════════════════════════════════════"
echo "   KIKI Academy — деплой на сервер"
echo "════════════════════════════════════════════════════════════"
echo ""

if ! command -v docker >/dev/null 2>&1; then
  warn "Docker не установлен."
  read -rp "Установить Docker и docker compose? (требует sudo) [y/N]: " inst
  if [[ "$inst" =~ ^[Yy]$ ]]; then
    info "Устанавливаем Docker через официальный скрипт…"
    curl -fsSL https://get.docker.com | sudo sh
    sudo usermod -aG docker "$USER" || true
    ok "Docker установлен. Возможно нужно перелогиниться, чтобы группа docker применилась."
  else
    fail "Docker нужен для деплоя. Прервано."
  fi
fi

if ! docker compose version >/dev/null 2>&1; then
  fail "docker compose plugin не доступен. Установите его и повторите."
fi
ok "Docker готов"

# ─── 1. Если .env уже существует — спрашиваем что делать ───────
if [ -f "$ENV_FILE" ]; then
  warn ".env уже существует — используем существующие значения."
  read -rp "Перезаписать .env заново (старые данные потеряются)? [y/N]: " recreate
  if [[ "$recreate" =~ ^[Yy]$ ]]; then
    rm "$ENV_FILE"
  fi
fi

# ─── 2. Запрос параметров ──────────────────────────────────────
if [ ! -f "$ENV_FILE" ]; then
  echo ""
  echo "── Параметры сайта ──"
  read -rp "Домен (например academy.kiki.kg): " DOMAIN
  [ -z "$DOMAIN" ] && fail "Домен обязателен"

  read -rp "Email для Let's Encrypt (для уведомлений о сертификате): " EMAIL
  [ -z "$EMAIL" ] && fail "Email обязателен"

  read -rp "Использовать тестовый (staging) сертификат? [y/N]: " STG
  STAGING_FLAG=""
  [[ "$STG" =~ ^[Yy]$ ]] && STAGING_FLAG="staging"

  echo ""
  echo "── Администратор (FOUNDER) ──"
  read -rp "Телефон администратора (+996…): " FOUNDER_PHONE
  read -rsp "Пароль администратора: " FOUNDER_PASSWORD; echo
  [ -z "$FOUNDER_PHONE" ] || [ -z "$FOUNDER_PASSWORD" ] && fail "Телефон и пароль обязательны"
  read -rp "Имя администратора: " FOUNDER_FIRST_NAME
  read -rp "Фамилия администратора: " FOUNDER_LAST_NAME

  echo ""
  info "Генерируем секреты…"
  SECRET_KEY=$(openssl rand -hex 32)
  POSTGRES_PASSWORD=$(openssl rand -hex 16)

  cat > "$ENV_FILE" <<ENV
# Generated by deploy.sh on $(date)
SECRET_KEY=$SECRET_KEY
DEBUG=False
ALLOWED_HOSTS=$DOMAIN,localhost,127.0.0.1
CSRF_TRUSTED_ORIGINS=https://$DOMAIN
SECURE_COOKIES=True

LANGUAGE_CODE=ru
TIME_ZONE=Asia/Bishkek

POSTGRES_DB=kikiacademy
POSTGRES_USER=kikiacademy_user
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
POSTGRES_HOST=db_kikiacademy
POSTGRES_PORT=5432

DEFAULT_STAFF_PASSWORD=12345678

# Параметры для повторного деплоя (используются deploy.sh)
KIKI_DOMAIN=$DOMAIN
KIKI_EMAIL=$EMAIL
KIKI_STAGING=$STAGING_FLAG
KIKI_FOUNDER_PHONE=$FOUNDER_PHONE
KIKI_FOUNDER_PASSWORD=$FOUNDER_PASSWORD
KIKI_FOUNDER_FIRST_NAME=$FOUNDER_FIRST_NAME
KIKI_FOUNDER_LAST_NAME=$FOUNDER_LAST_NAME
ENV
  ok ".env создан"
else
  # shellcheck disable=SC1090
  set -a; source "$ENV_FILE"; set +a
  DOMAIN="$KIKI_DOMAIN"
  EMAIL="$KIKI_EMAIL"
  STAGING_FLAG="$KIKI_STAGING"
  FOUNDER_PHONE="$KIKI_FOUNDER_PHONE"
  FOUNDER_PASSWORD="$KIKI_FOUNDER_PASSWORD"
  FOUNDER_FIRST_NAME="$KIKI_FOUNDER_FIRST_NAME"
  FOUNDER_LAST_NAME="$KIKI_FOUNDER_LAST_NAME"
fi

# ─── 3. Генерируем nginx конфиг (этап 1: HTTP-only) ───────────
info "Генерируем Nginx HTTP-конфиг для $DOMAIN…"
mkdir -p "$SCRIPT_DIR/nginx/conf.d"
DOMAIN="$DOMAIN" envsubst '$DOMAIN' < "$SCRIPT_DIR/nginx/templates/app-http.conf.template" \
  > "$SCRIPT_DIR/nginx/conf.d/app.conf"
ok "Nginx-конфиг готов"

# ─── 4. Билдим и запускаем контейнеры (без certbot) ───────────
info "Собираем и запускаем контейнеры (db_kikiacademy, redis_kikiacademy, web_kikiacademy, nginx_kikiacademy)…"
$COMPOSE up -d --build db_kikiacademy redis_kikiacademy web_kikiacademy nginx_kikiacademy

info "Ждём пока web-контейнер готов…"
sleep 8

# ─── 5. Создаём суперюзера ────────────────────────────────────
info "Создаём администратора (FOUNDER)…"
$COMPOSE exec -T web_kikiacademy python manage.py create_founder \
  --phone "$FOUNDER_PHONE" \
  --password "$FOUNDER_PASSWORD" \
  --first-name "$FOUNDER_FIRST_NAME" \
  --last-name "$FOUNDER_LAST_NAME"
ok "Администратор создан"

# ─── 6. Получаем SSL и переключаем Nginx на HTTPS ─────────────
echo ""
info "Получаем SSL-сертификат от Let's Encrypt…"
bash "$SCRIPT_DIR/init-letsencrypt.sh" "$DOMAIN" "$EMAIL" "$STAGING_FLAG"

# ─── 7. Запускаем certbot для автоматического renewal ─────────
info "Запускаем certbot-контейнер для auto-renewal…"
$COMPOSE up -d certbot_kikiacademy
ok "Certbot настроен (renewal каждые 12 часов)"

# ─── 8. Готово ────────────────────────────────────────────────
echo ""
echo "════════════════════════════════════════════════════════════"
ok "Деплой завершён!"
echo ""
echo "  Сайт:         https://$DOMAIN"
echo "  Админка:      https://$DOMAIN/staff/"
echo "  Логин:        $FOUNDER_PHONE"
echo "  Пароль:       (заданный при деплое)"
echo ""
echo "  Управление контейнерами:"
echo "    docker compose -f $COMPOSE_FILE ps"
echo "    docker compose -f $COMPOSE_FILE logs -f web_kikiacademy"
echo "    docker compose -f $COMPOSE_FILE restart web_kikiacademy"
echo ""
echo "════════════════════════════════════════════════════════════"
