# Generated by Django 6.0.3 on 2026-05-10 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_seed_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='code',
            field=models.CharField(choices=[('CLEANER', 'Cleaner'), ('MANAGER', 'Manager'), ('OPERATOR', 'Operator'), ('HR', 'HR'), ('FOUNDER', 'Founder')], max_length=32, unique=True),
        ),
    ]
