# Generated by Django 6.0.3 on 2026-05-16 19:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_alter_course_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='fired_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата увольнения'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hired_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата найма'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='users', to='lms.role', verbose_name='Роли'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Активен'), ('BLOCKED', 'Заблокирован'), ('FIRED', 'Уволен')], default='ACTIVE', max_length=16, verbose_name='Статус'),
        ),
    ]
