# Generated by Django 6.0.3 on 2026-05-17 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0007_alter_course_options_course_icon_course_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Текст ответа')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильный')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
                'ordering': ['question_id', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LessonBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('TEXT', 'Текст'), ('IMAGE', 'Изображение'), ('VIDEO', 'Видео')], default='TEXT', max_length=16, verbose_name='Тип блока')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
                ('image', models.ImageField(blank=True, null=True, upload_to='lessons/images/', verbose_name='Изображение')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Подпись')),
                ('video_url', models.URLField(blank=True, verbose_name='URL видео (YouTube / Vimeo)')),
            ],
            options={
                'verbose_name': 'Блок урока',
                'verbose_name_plural': 'Блоки урока',
                'ordering': ['lesson_id', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['lesson_id', 'order', 'id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='lesson',
            name='uniq_lesson_order_per_topic',
        ),
        migrations.RemoveConstraint(
            model_name='topic',
            name='uniq_topic_order_per_course',
        ),
        migrations.RemoveField(
            model_name='course',
            name='is_published',
        ),
        migrations.AddField(
            model_name='lesson',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание / введение'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликован'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='kind',
            field=models.CharField(choices=[('CONTENT', 'Контент'), ('QUIZ', 'Тест')], default='CONTENT', max_length=16, verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='lessonblock',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='lms.lesson', verbose_name='Урок'),
        ),
        migrations.AddField(
            model_name='question',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='lms.lesson', verbose_name='Урок'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='lms.question', verbose_name='Вопрос'),
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='content',
        ),
    ]
