# Generated by Django 5.2 on 2026-05-31 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0008_answer_lessonblock_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonprogress',
            name='attempts',
            field=models.PositiveIntegerField(default=0, verbose_name='Число попыток'),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='score_pct',
            field=models.PositiveIntegerField(default=0, verbose_name='Последний результат теста, %'),
        ),
    ]
