# Generated by Django 5.2 on 2026-06-10 19:57

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0012_userprofile_full_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonblock',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=False, null=True, quality=82, scale=None, size=[1600, 1600], upload_to='lessons/images/', verbose_name='Изображение'),
        ),
    ]
