# Generated by Django 5.2 on 2026-07-04 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0014_quizattempt'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='quizattempt',
            new_name='lms_quizatt_user_id_7c116d_idx',
            old_name='lms_quizatt_user_id_3d6f1a_idx',
        ),
    ]
